# Generated by Django 5.1.2 on 2025-02-23 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLogOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('event_type', models.CharField()),
                ('event_date_time', models.DateTimeField()),
                ('environment', models.CharField()),
                ('event_context', models.TextField()),
                ('metadata_version', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
